### ISSUE TITLE
Add HTML to modules folder and parse module html

### ISSUE THREAD

**Issue by anselmh** [use-init/init#129]
As discussed in #127 we want to add support to store and use HTML in the modules folder, too. It shouldn't be necessary to use it but optional.

**Comment by drublic** [comment]
Looks good to me. Can you please merge this?

**Comment by drublic** [comment]
Ah… it already is. Gotta close the issue now :)

**Comment by anselmh** [comment]
Sorry, forgot to close it.

----
Anselm
