### ISSUE TITLE
Getting error when I run Grunt

### ISSUE THREAD

**Issue by jitendravyas** [use-init/init#134]
![1 zsh a1zj0](https://cloud.githubusercontent.com/assets/77309/5633447/7973d67c-95fd-11e4-8e22-3a612a958a34.jpg)

**Comment by anselmh** [comment]
Hi, which version do you use and could you please post the code that is mentioned in the error log? Because, by default we don’t have livereload enabled so it might be an issue with your custom options?

**Comment by drublic** [comment]
It does not look like our configuration. Please post your config here. Looks like you forgot a `,` or something.

**Comment by drublic** [comment]
Will close this for now. Thanks for reporting though.
